const fs = require("fs");

const root = __dirname + "/../../../";
const { path } = require(root + "package.json").viewer;
const entries = [];

const readDir = dir => {
  fs.readdirSync(dir, "utf8").forEach(filename => {
    const path = dir + "/" + filename;
    if (fs.lstatSync(path).isDirectory()) {
      readDir(path);
    } else if (filename.endsWith(".js") && filename.split(".").length === 2) {
      if (filename[0] === filename[0].toUpperCase()) {
        const name = filename.replace(".js", "");
        if (!!entries.find(e => e.name === name)) {
          return;
        }
        const mockPath = path.replace(name, name + ".mock");
        entries.push({
          name,
          path,
          mockPath: fs.existsSync(mockPath) ? mockPath : undefined
        });
      }
    }
  });
};

readDir(path);

const imports = entries
  .map(c => {
    const mockImport = c.mockPath
      ? `import ${c.name}Mock from "../../../${c.mockPath}";\r\n`
      : "";
    return `import ${c.name} from "../../../${c.path}";\r\n${mockImport}`;
  })
  .join("");

const items = entries
  .map(c => {
    const mock = c.mockPath ? `, mock: ${c.name}Mock ` : "";
    return `  { name: '${c.name}', Component: ${c.name}${mock} }`;
  })
  .join(",\r\n");

const data = `/* This file has been generated by a script */

${imports}
export const items = [
${items}
];
`;

fs.writeFileSync(root + "src/viewer/generated/meta.js", data);
